/* ALRAEBI AUTO CARS — FINAL MASTER cloud-first bridge */
(()=>{
 const api=window.RACAPI;if(!api)return;
 const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
 const localMap=c=>({id:String(c.id),name:c.name,brand:c.make||c.brand||'',type:c.type||'',year:c.year||'',fuel:c.fuel||'',drive:c.transmission||c.drive||'4×4',img:(c.images&&c.images[0])||c.img||'images/car-1.jpg',tag:c.featured?'مميزة':'متوفر',stock:c.status==='sold'?'مباع':c.status==='reserved'?'محجوز':'متوفر',price:c.price?`${c.price} ${c.currency||'USD'}`:'اتصل للسعر',description:c.description||'' ,features:[]});
 async function sync(){try{const x=await api.cars({status:'available',limit:100});if(x.items?.length){window.cars=x.items.map(localMap);try{localStorage.setItem('alraebi_cloud_cache',JSON.stringify(window.cars))}catch{};if(typeof render==='function')render();const s=document.querySelector('[data-v11-stat="cars"]');if(s)s.textContent=x.total;return true}}catch(e){}return false}
 window.RACCloudMaster={sync,api};
 window.v19CustomerLogin=async()=>{const phone=prompt('رقم الهاتف');if(!phone)return;const password=prompt('كلمة المرور');if(!password)return;try{const x=await api.customerLogin({phone,password});localStorage.setItem('rac_customer',JSON.stringify(x.customer));alert('تم تسجيل الدخول بنجاح');location.reload()}catch(e){alert(e.message)}};
 window.v19CustomerRegister=async()=>{const name=prompt('الاسم');if(!name)return;const phone=prompt('رقم الهاتف');if(!phone)return;const password=prompt('كلمة المرور — 6 أحرف على الأقل');if(!password)return;try{await api.customerRegister({name,phone,password});alert('تم إنشاء الحساب، سجّل الدخول الآن')}catch(e){alert(e.message)}};
 window.v19CustomerOrders=async()=>{if(!api.isCustomer())return v19CustomerLogin();try{const [me,orders,notes]=await Promise.all([api.me(),api.myOrders(),api.notifications()]);const lines=orders.map(o=>`#${o.id} — ${esc(o.car_name||'طلب')} — ${esc(o.status)}`).join('<br>')||'لا توجد طلبات بعد';const modal=document.createElement('div');modal.className='rac-master-modal';modal.innerHTML=`<div class="rac-master-box"><button onclick="this.closest('.rac-master-modal').remove()">×</button><h2>حسابي</h2><p>${esc(me.name)} — ${esc(me.phone)}</p><h3>طلباتي</h3><div>${lines}</div><h3>الإشعارات</h3><div>${notes.map(n=>`<div class="rac-note"><b>${esc(n.title)}</b><br>${esc(n.body||'')}</div>`).join('')||'لا توجد إشعارات'}</div><button class="btn" onclick="RACAPI.customerLogout();location.reload()">تسجيل الخروج</button></div>`;document.body.appendChild(modal)}catch(e){alert(e.message)}};
 window.racCloudOrder=async c=>{const name=prompt('الاسم');if(!name)return;const phone=prompt('رقم الهاتف');if(!phone)return;const notes=prompt('ملاحظات إضافية')||'';try{const x=await api.order({customer_name:name,phone,car_id:c.id,car_name:c.name,notes});alert('تم استلام طلبك رقم #'+x.id)}catch(e){alert(e.message)}};
 window.racCloudDrive=async c=>{const name=prompt('الاسم');if(!name)return;const phone=prompt('رقم الهاتف');if(!phone)return;const date=prompt('التاريخ YYYY-MM-DD');if(!date)return;const time=prompt('الوقت HH:MM','16:00')||'16:00';try{const x=await api.appointment({name,phone,date,time,car_id:c.id,car_name:c.name});alert('تم حجز الطلب رقم #'+x.id)}catch(e){alert(e.message)}};
 document.addEventListener('DOMContentLoaded',async()=>{const ok=await sync();const el=document.createElement('div');el.className='rac-master-cloud';el.innerHTML=ok?'☁️ <b>ONLINE</b> — CLOUD MASTER':'◉ LOCAL MODE';document.body.appendChild(el);});
})();
