/* ALRAEBI AUTO CARS V19 — CLOUD-FIRST EXPERIENCE */
(function(){
  const customerKey='rac_customer_token';
  const localKey='rac_v19_customer';
  const base=()=> (localStorage.getItem('rac_api_base')||'/api').replace(/\/$/,'');
  const ctoken=()=>localStorage.getItem(customerKey)||'';
  async function cReq(path,opt={}){const h={...(opt.headers||{})}; if(opt.body&&!(opt.body instanceof FormData))h['Content-Type']='application/json'; if(ctoken())h.Authorization='Bearer '+ctoken(); const r=await fetch(base()+path,{...opt,headers:h}); const d=await r.json().catch(()=>({})); if(!r.ok)throw Error(d.error||('HTTP '+r.status)); return d}
  function toast(t){if(window.V11?.toast)V11.toast(t);else if(window.toast)window.toast(t);}
  function imgUrl(src){if(!src)return 'images/car-1.jpg'; if(/^https?:\/\//.test(src))return src; const b=localStorage.getItem('rac_api_base'); if(b&&b.startsWith('http')&&src.startsWith('/'))return b.replace(/\/api\/?$/,'')+src; return src;}
  function mapCar(c){return {id:String(c.id),name:c.name,brand:c.make||c.brand||'',year:c.year||'',price:c.price||0,type:c.type||'',fuel:c.fuel||'',drive:c.drive||c.transmission||'',stock:(c.quantity??1)>0?'متوفر الآن':'غير متوفر',tag:c.featured?'مميز':'متوفر',img:imgUrl((c.images&&c.images[0])||c.img||c.image),images:(c.images||[]).map(imgUrl),description:c.description||''};}
  async function syncCars(){try{const d=await fetch(base()+'/cars?status=available&limit=100').then(r=>r.json()); if(!d.items || !d.items.length)return; const mapped=d.items.map(mapCar); window.racV19CloudCars=mapped; try{cars=mapped}catch(e){}; if(typeof render==='function')render(); document.documentElement.classList.add('rac-v19-online'); const st=document.getElementById('racV19State');if(st){st.textContent='ONLINE';st.style.color='#65e6a1'}; return mapped}catch(e){const st=document.getElementById('racV19State');if(st)st.textContent='LOCAL';}}
  async function cloudLead(type,car){const n=document.getElementById('v11Name')?.value?.trim()||prompt('الاسم')||''; const p=document.getElementById('v11Phone')?.value?.trim()||prompt('رقم الهاتف')||''; if(!n||!p)return; const note=document.getElementById('v11Note')?.value?.trim()||''; try{await cReq('/leads',{method:'POST',body:JSON.stringify({name:n,phone:p,type:type||'inquiry',car_name:car||'',notes:note})});toast('تم إرسال الطلب للمعرض');}catch(e){toast('تعذر الاتصال بالسيرفر — تم حفظ الطلب محلياً');}}
  window.racV19={syncCars,cReq,mapCar,imgUrl,cloudLead,logout(){localStorage.removeItem(customerKey);localStorage.removeItem(localKey);toast('تم تسجيل الخروج')}};
  window.v19CustomerRegister=async function(){const name=prompt('الاسم');if(!name)return;const phone=prompt('رقم الهاتف');if(!phone)return;const password=prompt('كلمة المرور — 6 أحرف أو أكثر');if(!password)return;try{await cReq('/customers/register',{method:'POST',body:JSON.stringify({name,phone,password})});toast('تم إنشاء الحساب، سجّل الدخول الآن')}catch(e){toast(e.message)}};
  window.v19CustomerLogin=async function(){const phone=prompt('رقم الهاتف');if(!phone)return;const password=prompt('كلمة المرور');if(!password)return;try{const x=await cReq('/customers/login',{method:'POST',body:JSON.stringify({phone,password})});localStorage.setItem(customerKey,x.token);localStorage.setItem(localKey,JSON.stringify(x.customer));toast('مرحباً '+x.customer.name);window.v19CustomerOrders()}catch(e){toast(e.message)}};
  window.v19CustomerOrders=async function(){try{const me=await cReq('/customers/me'),os=await cReq('/customers/me/orders'); const m=document.getElementById('modal'); if(!m)return; m.classList.add('show'); const box=document.getElementById('modalContent'); box.innerHTML='<button class="close" onclick="closeModal()">×</button><h2>حسابي السحابي</h2><p class="muted">'+me.name+' • '+me.phone+'</p><h3>طلباتي</h3>'+((os||[]).map(o=>'<div class="stat" style="margin:8px 0"><b>'+((o.car_name||'طلب سيارة'))+'</b><span>'+o.status+' • '+o.created_at+'</span></div>').join('')||'<p class="muted">لا توجد طلبات بعد.</p>');}catch(e){toast('سجّل الدخول أولاً')}};
  document.addEventListener('DOMContentLoaded',()=>{syncCars(); setTimeout(()=>{const box=document.getElementById('v13CustomerBox');if(box&&!document.getElementById('v19CloudButtons')){const d=document.createElement('div');d.id='v19CloudButtons';d.className='v13-actions';d.style.justifyContent='center';d.innerHTML='<button class="btn primary" onclick="v19CustomerLogin()">دخول سحابي</button><button class="btn" onclick="v19CustomerRegister()">إنشاء حساب سحابي</button><button class="btn" onclick="v19CustomerOrders()">طلباتي السحابية</button>';box.appendChild(d)}} ,300)});
})();
